# Generated by Django 2.0.5 on 2018-08-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20180808_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('crm_table_list', '可以查看useradmin每张表里所有的数据'), ('crm_table_list_view', '可以访问useradmin表里每条数据的修改页'), ('crm_table_list_change', '可以对useradmin表里的每条数据进行修改'), ('crm_table_obj_add_view', '可以访问useradmin每张表的数据增加页'), ('crm_table_obj_add', '可以对useradmin每张表进行数据添加'))},
        ),
    ]
