# Generated by Django 2.0.5 on 2018-08-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20180808_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='afsa@123.com', max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
