# Generated by Django 2.0.5 on 2018-08-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20180808_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(blank=True, to='crm.Role'),
        ),
    ]
